---

- hosts: node
  gather_facts: no
  become: true
  
  tasks:
  - name: Get the artifact from Artifactory
    maven_artifact:
     group_id: com.wakaleo.gameoflife
     artifact_id: gameoflife-web
     repository_url: 'http://192.168.189.246:8081/repository/maven-public'
     extension: war
     username: admin
     password: 341Zbojw@
     dest: /home/ansible
     owner: ansible
     group: ansible
     mode: u=rw,g=r,o=r
        
  - name: create docker custom image
    docker_image:
     build:
      path: /home/ansible/
     name: tomcat_gameoflife
  
  - name: starting container
    docker_container:
     name: gameoflife
     state: started
     ports:
     - "8090:8080"
     tty: true
     detach: true
  
     
      
