---
- hosts: node
  become: true
  
  tasks:
  - name: Get the artifact from Artifactory
    maven_artifact:
     group_id: com.wakaleo.gameoflife
     artifact_id: gameoflife-web
     repository_url: 'http://192.168.189.246:8081/#browse/browse:maven-public'
     extension: war
     username: admin
     password: 341Zbojw@
     dest: /home/ansible
     owner: ansible
     mode: u=rw,g=r,o=r
     
      
