kind: Deployment
apiVersion: apps/v1
metadata:
 name: sesapp
 namespace: default
spec:
 replicas: 2
 selector:
  matchLabels:
   myapp: sesapp
 template:
  metadata:
   labels:
    myapp: sesapp
  spec:
   containers:
   - name: sesapp
     image: tomcat:9.0.31
     volumeMounts:
     - name: app
       mountPath: /usr/local/tomcat/webapps
   volumes:
   - name: app
     hostPath:
      path: /home/master/kubernetes

---

kind: Service
apiVersion: v1
metadata:
 name: sesapp
 namespace: default
spec:
 type: NodePort
 selector:
  myapp: sesapp
 ports:
 - port: 8081
   targetPort: 8080
   nodePort: 30010
